fs = require 'fs'
stitch  = require 'stitch'
{parser, uglify} = require 'uglify-js'

option '-m', '--minify', 'Minify output'

output_dir = __dirname + '/../assets/js'

task 'build', 'Build app', (options) ->
	app = stitch.createPackage
		paths: [__dirname + '/lib']
		dependencies:[
			__dirname + '/vendor/jquery.mousewheel.js'
			__dirname + '/vendor/jquery-ui-1.8.23.custom.js'
			__dirname + '/vendor/spin.js'
		]

	app.compile (err, source) ->
		if err then throw err

		fs.mkdir output_dir, 0o775, (err) ->
			if err and err.code isnt 'EEXIST' then throw err

			fs.writeFile output_dir + '/app.js', source, (err) ->
				if err then throw err

				if options.minify
					ast = parser.parse source
					minified = uglify.gen_code uglify.ast_squeeze uglify.ast_mangle ast, extra: yes

					fs.writeFileSync output_dir + '/app.js', minified, "utf-8"
					console.log 'Compiled and minified app.js'
				else
					console.log 'Compiled app.js'
